<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../../src/Core/PorterRules.cs" Link="Core/PorterRules.cs" />
    <Compile Include="../../src/Core/PorterServerRequestRules.cs" Link="Core/PorterServerRequestRules.cs" />
  </ItemGroup>
</Project>
